// Real product output for an actual case-study client, generated by the backend
// over the SwissHacks case-study data (the provided CRM + Portfolio workbooks)
// via get_insights / build_risk_timeline. Kept here so the pitch shows the
// product's real generated text and numbers — not invented copy.

export const BRAND = {
  name: "Everyone's a Billionaire",
  credit: "SwissHacks · SIX / Noumena / NTT DATA",
};

export const DESK: {
  name: string;
  mandate: string;
  alerts: number;
  polarity: "conflict" | "opportunity";
  note: string;
}[] = [
  { name: "Hubertus Schneider", mandate: "Balanced", alerts: 3, polarity: "conflict", note: "Biogen conflicts with his neuro-research stance" },
  { name: "Julian Ammann", mandate: "Growth", alerts: 3, polarity: "conflict", note: "PDD Holdings — labour-governance scandal" },
  { name: "Eugen Räber", mandate: "Defensive", alerts: 3, polarity: "conflict", note: "Signal pushes into US mega-cap tech he avoids" },
  { name: "Marius Huber", mandate: "Defensive", alerts: 2, polarity: "opportunity", note: "Unilever acts on deforestation — values-aligned" },
];

// --- Workflow composition: news → classify → collide → kanban → alert → review.
// Mirrors the real product task board (statuses backlog → started/in-progress →
// review/"Needs sign-off"); task copy + activity trail are the actual task-0008.
export const WORKFLOW = {
  article: {
    outlet: "FINANCIAL WIRE",
    url: "ft.example/markets/biogen-neuro",
    date: "20 June 2026",
    headline: "Biogen to wind down its neurodegenerative research division",
    standfirst:
      "The biotech will halt several brain-disease programmes and pivot to higher-margin therapeutics, drawing sharp criticism from patient foundations.",
    body: [
      "Biogen confirmed it will shut its dedicated neurodegenerative research division, halting several early-stage programmes as it redirects capital toward higher-margin therapeutics.",
      "Advocacy groups that have long funded brain-disease research called the move “a betrayal of patients”.",
    ],
  },
  classify: {
    sentiment: "BEARISH",
    score: -0.62,
    topic: "Neurodegenerative research",
  },
  collision: {
    client: "Mr. Schneider",
    stance: "His foundation funds Parkinson’s research.",
    holding: "Held: Biogen Inc. · CHF 101,097",
    source: "schneider#…#1",
  },
  task: {
    title: "Risk review: Biogen Inc. conflicts on Neurodegenerative research",
    client: "Schneider",
    priority: "High",
    activity: [
      "Agent picked up task (investment_review).",
      "Matched signal ‘Biogen to wind down neurodegenerative research’ (conflict).",
      "Ran advisory engine — 1 action proposed.",
      "Draft ready — parked in ‘Needs sign-off’ for RM.",
    ],
    finding: "Proposed SWAP within mandate — Biogen Inc. → Eli Lilly & Co. (CHF 101,097)",
  },
  alert: {
    time: "09:00",
    sender: "Advisory Workbench",
    text:
      "Good morning. 1 item needs your review: Mr. Schneider — Biogen conflicts with his neuro-research stance. A same-sector swap is ready. Open the workbench →",
  },
};

// News & signal watch — classify-once corpus over the seed/case-study book.
export const NEWS = {
  total: 21,
  topics: 4,
  sources: [
    { label: "News", n: 6 },
    { label: "SEC filings", n: 6 },
    { label: "ESG", n: 2 },
    { label: "Earnings", n: 2 },
    { label: "Analyst", n: 1 },
    { label: "Macro", n: 4 },
  ],
  items: [
    { type: "NEWS", sentiment: "BEARISH" as const, score: "−0.62", topic: "Neuro research", title: "Biogen to wind down its neurodegenerative research division" },
    { type: "ESG", sentiment: "BULLISH" as const, score: "+0.71", topic: "Deforestation", title: "Unilever cuts off palm-oil suppliers tied to deforestation" },
    { type: "SEC FILING", sentiment: "BEARISH" as const, score: "−0.68", topic: "Labour governance", title: "PDD Holdings (Temu) hit with forced-labour allegations" },
    { type: "ANALYST", sentiment: "BULLISH" as const, score: "+0.34", topic: "US tech / AI", title: "CIO tactical update: rotate into mega-cap US tech" },
  ],
};

// Rendezvous — plan the client meeting, grounded in their record + optimised.
export const RENDEZVOUS = {
  client: "Eugen Räber",
  interests: [
    "Engineering & hardware",
    "Quiet, classical tastes",
    "Flims & the mountains",
    "Dependable dividends",
    "Wealth for the grandchildren",
  ],
  venues: [
    { title: "Lunch at the Kronenhalle", city: "Zürich", when: "Weekday · 12:30", why: "Old-world, discreet and utterly dependable — tangible quality." },
    { title: "Beyer Watch & Clock Museum", city: "Zürich", when: "By appointment", why: "He respects firms that build real, physical machinery." },
    { title: "Evening at the Tonhalle", city: "Zürich", when: "Friday · 19:30", why: "A measured, classical evening matches his temperament." },
  ],
  optimiser: {
    headline: "Fairest place to convene 3 attendees · Zürich",
    chips: ["0 kg CO₂", "CHF 159 travel", "longest leg 0.2h"],
    modes: ["Fairest", "Greenest"],
    note: "live flight quotes · day/night globe",
  },
};

// Client digital twin — a real "bounce then clear" loop for Julian Ammann
// (Growth; non-negotiable stance on labour & supply-chain governance).
export const TWIN = {
  client: "Julian Ammann",
  concern: {
    quote: "My national brand equity is built on clean labour — that's non-negotiable.",
    date: "Jun 2023",
    source: "ammann#…#3",
  },
  attempt1: {
    move: "Rebalance the consumer sleeve into PDD Holdings",
    verdict: "Likely to object",
    reason:
      "Buys into labour-risk — conflicts with his stance on labour & supply-chain governance.",
    says: "Not after the supply-chain reports.",
    source: "ammann#…#3",
  },
  attempt2: {
    move: "Same sector — Cie Financière Richemont instead",
    amount: "CHF 95,688",
    verdict: "Likely receptive",
    reason:
      "Clean-governance, comparable risk (+1.1% vol) — it backs exactly what he champions.",
    source: "cio_list",
  },
};

export const SCHNEIDER = {
  name: "Hubertus Schneider",
  mandate: "Balanced",
  alert: {
    polarity: "conflict" as const,
    text:
      "Biogen Inc. puts a holding in conflict with this client's stance on Neurodegenerative research.",
    source: "esg:biogen-cut",
  },
  swap: {
    action: "SWAP",
    sell: "Biogen Inc.",
    buy: "Eli Lilly & Co.",
    amount: "CHF 101,097",
    rationale:
      "Divest Biogen (CIO: HOLD) — the trigger violates his documented stance on neurodegenerative research. Reinvest into Eli Lilly (CIO: BUY), a same-sector name labelled neuro-research-commitment — keeps the sector weight, upgrades the values fit at comparable risk.",
    constraints: [
      "CIO-approved names only",
      "Same sector · Health Care",
      "Risk-matched · 19% → 22% vol",
      "Drift-neutral · within ±2.0pp",
    ],
    source: "cio_list",
  },
  dialogue: {
    style:
      "Empathetic and mission-driven. Hubertus is an analytical automotive CEO, but since his daughter Chloe's diagnosis his decisions are driven by purpose. Lead with the human stake, then the facts.",
    draft:
      "Dear Schneider, a development needs your attention: Biogen to wind down its neurodegenerative research division, pivoting to higher-margin therapeutics. Because it touches your stance and a current holding, I have prepared a same-sector, CIO-approved option that keeps your strategy intact while restoring the values fit.",
    points: [
      "Connects to what Hubertus told us about neurodegenerative research.",
      "Directly affects a current holding: Biogen Inc. (CHF 101,097).",
    ],
  },
  risk: {
    scores: [
      0.62, 0.41, 0.34, 0.34, 0.27, 0.27, 0.34, 0.27, 0.2, 0.05, 0.05, 0.05,
      0.05, 0.05, 0.05, 0.05, 0.05, 0.12, 0.12, 0.19, 0.19, 0.19, 0.19, 0.19,
      0.19, 0.19,
    ],
    baseline: 0.55,
    band: [0.43, 0.67] as [number, number],
    from: "Apr 2023",
    to: "May 2026",
    fit: "cautious-drift",
    // Real milestones from build_risk_timeline — the events that moved the line.
    events: [
      { i: 1, date: "Jun 2023", label: "Drifts defensive", cue: "raised liquidity needs" },
      { i: 9, date: "Nov 2024", label: "De-risking signal", cue: "“long-term” horizon" },
      { i: 16, date: "Nov 2025", label: "De-risking signal", cue: "“protect” capital" },
    ],
    // X-axis ticks at real point dates.
    ticks: [
      { i: 0, label: "Apr ’23" },
      { i: 8, label: "Sep ’24" },
      { i: 16, label: "Nov ’25" },
      { i: 25, label: "May ’26" },
    ],
  },
};
